"""Persistence, process scheduling and numerical execution are replaceable adapters."""

from typing import Callable, Protocol

from .domain import Run

Progress = Callable[[dict], None]
Cancellation = Callable[[], bool]


class RunRepository(Protocol):
    def create(self, run: Run) -> Run: ...
    def get(self, identifier: str) -> Run: ...
    def list(self) -> list[Run]: ...
    def update(self, run: Run, expected_status: str | None = None) -> Run: ...
    def delete(self, identifier: str) -> None: ...


class RunReferences(Protocol):
    def run_in_use(self, identifier: str) -> bool: ...


class SchedulerPort(Protocol):
    def start(self, run: Run) -> None: ...
    def cancel(self, identifier: str) -> None: ...
    def close(self) -> None: ...
    def events(self, identifier: str) -> list[dict]: ...


class EnginePort(Protocol):
    def run(self, spec: dict, progress: Progress, cancelled: Cancellation) -> dict: ...
