"""Revision storage and adapter-aware validation of user recipes."""

from typing import Callable, Protocol

from .domain import Recipe

RecipeValidator = Callable[[str, dict], None]


class RecipeRepository(Protocol):
    def list(self, kind: str, query: str = "") -> list[Recipe]: ...
    def get(self, identifier: str, kind: str | None = None, revision: int | None = None) -> Recipe: ...
    def create(self, recipe: Recipe) -> Recipe: ...
    def update(self, recipe: Recipe, expected_revision: int) -> Recipe: ...
    def delete(self, identifier: str, kind: str | None = None) -> None: ...
